CREATE TABLE devices (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         device_id VARCHAR(100) NOT NULL,

                         hashed_device_token VARCHAR(255) NOT NULL,

                         user_id VARCHAR(100) NOT NULL,

                         name VARCHAR(100),
                         location VARCHAR(255),

                         CONSTRAINT uk_devices_device_id UNIQUE (device_id),

                         INDEX idx_devices_user_id (user_id)
);

-- (Опционально) Индекс для быстрого поиска по device_id, если нужно
-- CREATE INDEX idx_devices_device_id ON devices (device_id);