-- V1__Initial_schema.sql

-- User.java
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

-- (Device.java)
CREATE TABLE devices (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         location VARCHAR(255),
                         status VARCHAR(50) NOT NULL,
                         user_id BIGINT,
                         CONSTRAINT fk_devices_on_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- (DeviceData.java)
CREATE TABLE device_data (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             device_id BIGINT NOT NULL,
                             timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                             temperature DECIMAL(5, 2),
                             humidity DECIMAL(5, 2),
                             status VARCHAR(50),
                             CONSTRAINT fk_devicedata_on_device FOREIGN KEY (device_id) REFERENCES devices(id)
);

-- (Alert.java)
CREATE TABLE alerts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        device_id BIGINT NOT NULL,
                        message VARCHAR(255) NOT NULL,
                        timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                        acknowledged BOOLEAN DEFAULT FALSE,
                        CONSTRAINT fk_alerts_on_device FOREIGN KEY (device_id) REFERENCES devices(id)
);