CREATE TABLE device_view_history (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     user_id VARCHAR(255) NOT NULL,
                                     device_id VARCHAR(255) NOT NULL,
                                     viewed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     CONSTRAINT pk_device_view_history PRIMARY KEY (id)
);

CREATE INDEX idx_view_user_date ON device_view_history (user_id, viewed_at);