CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alert_id VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    message TEXT,
    value DOUBLE PRECISION,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_alerts PRIMARY KEY (id),
    CONSTRAINT uk_alerts_alert_id UNIQUE (alert_id)
);

CREATE INDEX idx_alerts_user_read_time ON alerts (user_id, is_read, timestamp DESC);